### model
model_name_or_path: Qwen/Qwen2.5-3B-Instruct
# model_name_or_path: Qwen/Qwen3-8B

### method
stage: sft
do_train: true
finetuning_type: full
deepspeed: examples/deepspeed/ds_z1_config.json

### dataset
dataset: new_energy_issues_sharegpt
template: qwen
cutoff_len: 1024
overwrite_cache: true
preprocessing_num_workers: 16

### output
output_dir: saves/qwen2-3b/full/sft/new_energy_issues_sharegpt
logging_steps: 50
save_steps: 500
plot_loss: true
overwrite_output_dir: true

### train
per_device_train_batch_size: 1
gradient_accumulation_steps: 8
learning_rate: 2.0e-5
num_train_epochs: 15.0
lr_scheduler_type: cosine
warmup_ratio: 0.1
bf16: true
ddp_timeout: 180000000
# resume_from_checkpoint: saves/qwen2-0.5b/full/sft/new_energy_issues_sharegpt/checkpoint-1500

## eval
eval_dataset: new_energy_issues_re_sharegpt
per_device_eval_batch_size: 1
eval_strategy: epoch
# eval_steps: 500

### wandb
report_to: wandb
run_name: qwen2-3b-full-new-energy-sharegpt # optional
