### model
# model_name_or_path: Qwen/Qwen3-1.7B
model_name_or_path: Qwen/Qwen3-8B

### method
stage: sft
do_train: true
finetuning_type: full
deepspeed: examples/deepspeed/ds_z1_config.json

### dataset
dataset: empowerfactory
template: qwen
cutoff_len: 1024
overwrite_cache: true
preprocessing_num_workers: 16

### output
output_dir: saves/qwen3-8b/full/sft/empowerfactory
logging_steps: 50
save_steps: 100
plot_loss: true
overwrite_output_dir: true

### train
per_device_train_batch_size: 1
gradient_accumulation_steps: 8
learning_rate: 1.0e-5
num_train_epochs: 3.0
lr_scheduler_type: cosine
warmup_ratio: 0.1
bf16: true
ddp_timeout: 180000000
### eval
# val_size: 0.1
# per_device_eval_batch_size: 1
# eval_strategy: steps
# eval_steps: 500

### wandb
# report_to: wandb
# run_name: qwen3-8b-full-empowerfactory # optional
