### model
model_name_or_path: Qwen/Qwen2.5-7B-Instruct

### method
stage: sft
do_train: true
finetuning_type: lora
lora_target: all
lora_rank: 16
lora_alpha: 32
lora_dropout: 0.05
# deepspeed: examples/deepspeed/ds_z3_config.json

### dataset
dataset: firepower_issues
template: qwen
cutoff_len: 2048
overwrite_cache: true
preprocessing_num_workers: 16
dataloader_pin_memory: true # 新增参数，启用内存锁页

### output
output_dir: saves/qwen2-7b/lora/firepower_issues
logging_steps: 50
save_steps: 500
plot_loss: true
overwrite_output_dir: true

### train
per_device_train_batch_size: 8
gradient_accumulation_steps: 16
learning_rate: 3.0e-4
num_train_epochs: 50.0
lr_scheduler_type: cosine
warmup_ratio: 0.1
bf16: true
ddp_timeout: 180000000
# resume_from_checkpoint: saves/qwen2-7b/lora/new_energy_issues/checkpoint-3000
# flash_attn: fa2

### eval
eval_dataset: firepower_issues_re
per_device_eval_batch_size: 1
eval_strategy: epoch
# eval_steps: 5

### wandb
report_to: wandb
run_name: qwen2-7b-lora-16-rank-32-firepower_issues # optional

