### model
model_name_or_path: /wekafs/takisobe/zxy/models/Qwen2.5-VL-7B-Instruct
image_max_pixels: 16777216
video_max_pixels: 16384
trust_remote_code: true

### method
stage: sft
do_train: true
finetuning_type: lora
lora_rank: 16
lora_target: all

### dataset
dataset: unsplash1-2          
template: qwen2_vl         
media_dir: /wekafs/takisobe/haisenhe/DataPipeline
cutoff_len: 131072
max_samples: 20000
overwrite_cache: true
preprocessing_num_workers: 64
dataloader_num_workers: 64

### output
output_dir: /wekafs/takisobe/zxy/models/sft/qwen-ir-unsplash1-2
logging_steps: 1
save_steps: 20
plot_loss: true
overwrite_output_dir: true
save_only_model: false
report_to: wandb  # choices: [none, wandb, tensorboard, swanlab, mlflow]
run_name: qwen2_5vl_unsplash1-2_only

### train
per_device_train_batch_size: 2
gradient_accumulation_steps: 2
learning_rate: 2.0e-4
num_train_epochs: 3.0
lr_scheduler_type: cosine
warmup_ratio: 0.1
weight_decay: 0.001
bf16: true
ddp_timeout: 180000000
resume_from_checkpoint: /wekafs/takisobe/zxy/models/sft/qwen-ir-unsplash1-2/checkpoint-80

### eval
val_size: 0.01
per_device_eval_batch_size: 1
eval_strategy: steps
eval_steps: 50
